[phases.setup]
nixPkgs = ["php82", "php82Packages.composer", "nodejs_18", "yarn", "nginx"]

[phases.install]
cmds = [
    "composer install --no-dev --optimize-autoloader --no-interaction",
    "chmod +x scripts/setup-permissions.sh",
    "./scripts/setup-permissions.sh"
]

[phases.build]
cmds = [
    "yarn install",
    "yarn build",
    "chmod +x scripts/deploy-setup.sh"
]

[phases.deploy]
cmds = [
    "./scripts/deploy-setup.sh"
]

[start]
cmd = "php artisan serve --host=0.0.0.0 --port=$PORT"

[variables]
PORT = "8080" 