[phases.setup]
nixPkgs = ["php82", "php82Packages.composer", "nodejs_18", "yarn", "nginx"]

[phases.install]
cmds = [
    "composer install --no-dev --optimize-autoloader --no-interaction",
    "chmod +x scripts/setup-permissions.sh",
    "./scripts/setup-permissions.sh",
    "chmod +x scripts/deploy-setup.sh",
    "chmod +x scripts/start.sh",
    "chmod +x scripts/health-check.sh"
]

[phases.build]
cmds = [
    "yarn install",
    "yarn build"
]

[start]
cmd = "bash scripts/start.sh"

[variables]
PORT = "8080" 