[phases.setup]
nixPkgs = ["php82", "php82Packages.composer", "nodejs_18", "nginx"]

[phases.install]
cmds = [
    "composer install --no-dev --optimize-autoloader --no-interaction",
    "npm ci --only=production",
    "chmod +x scripts/setup-permissions.sh",
    "./scripts/setup-permissions.sh"
]

[phases.build]
cmds = [
    "npm run build",
    "php artisan config:cache",
    "php artisan route:cache",
    "php artisan view:cache"
]

[start]
cmd = "php artisan serve --host=0.0.0.0 --port=$PORT"

[variables]
PORT = "8080" 